### ISSUE TITLE
DS&ALGO

### ISSUE THREAD

**Issue by Aravindravi1209** [0xStryK3R/Scaler-DSA-Revision#2]
Hi There, Can you ping me your linkedin Profile/mail id!! Have some queries regarding DS & ALGO!!

**Comment by 0xStryK3R** [comment]
@Aravindravi1209 hey, you can find the links in my [GitHub Profile Page](https://github.com/0xStryK3R)

**Comment by Aravindravi1209** [comment]
Hello Arup,

How are you? I am currently working in a support role, thought of learning
DS & ALGO, and have started my preparation!! Wanted to do some assignments
on a daily basis, which is when I came across your repo!! If the questions
were there, along with the solutions it would be better to practice first
and then check with your solutions!!

Me and my friend Sensi have started this together!! If you have the
questions segregated as the same as the solutions, please let me know if
you can share it!!

Thanks,
Aravind

**Comment by 0xStryK3R** [comment]
Hi Aravind, apologies but the questions are part of scaler curriculum and are proprietary to them, hence, I am not really at a liberty to share them publicly. 
However, if you do have any other queries regarding the queries do hmu in twitter/LinkedIn.

**Comment by 0xStryK3R** [comment]
There are a couple of free reference sources I have come across which you may find helpful:

[Strivers SDE sheet](https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/)

[Strivers A2Z DSA Course](https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/)
